server:
  port: ${PORT:0}
spring:
  application:
    name: packages-service
  config:
    import: optional:configserver:http://localhost:8888
  # rabbitMQ config for Spring Cloud Bus to be able to communicate
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://root:rootroot@0.0.0.0:27017/packagesservicedb?authSource=admin&retryWrites=true&w=majority #without '?authSource=admin' doesn't work
      database: packagesservicedb
      username: root
      password: rootroot
#        host: localhost
#        username: dbUser
#        password: dbPassword
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost

logging:
  level:
    com.example.demo: DEBUG

axon:
  serializer:
    general: jackson
    events: jackson
    messages: Jackson

#enable circuit breaker
feign:
  circuitbreaker:
    enabled: true