version: '3.8'
services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitmq-spring-cloud-config-server
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  #    RABBITMQ_DEFAULT_VHOST=my_vhost