version: '3.8'
services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitmq-spring-cloud-config-server
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ourNetwork

  mongoDB:
    image: mongo
    container_name: reactive-packages-service-mongoDB
    ports:
      - 27017:27017
#      - '27017-27019:27017-27019'
#    volumes:
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # initial script (executes only if /data/db is empty in container - never empty = never executes
#      - ~/home/workstation/dockerstorage/mongodbstorage:/data/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: packagesservicedb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot
    networks:
      - ourNetwork

  # Database Manager
#  mongo-express:
#    image: mongo-express
#    ports:
#      - 8099:8081
#    depends_on:
#      - mongo
#    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: express
#      ME_CONFIG_BASICAUTH_PASSWORD: 123456
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: rootroot
#    links:
#      - mongoDB

  axonFramework:
    image: axoniq/axonserver
    container_name: axon-framework
    ports:
      - 8024:8024
      - 8124:8124
    volumes:
      - /home/linuxmachine/dockerstorage/axon-docker/data:/data
      - /home/linuxmachine/dockerstorage/axon-docker/eventdata:/eventdata
      - /home/linuxmachine/dockerstorage/axon-docker/config:/config
    environment:
      AXONIQ_AXONSERVER_NAME: Axon Server
      AXONIQ_AXONSERVER_HOSTNAME: localhost
      SERVER_PORT: 8024
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: true #enable Axon Server to start up in development mode - it enables RESET button in dashboard. It can be used to clear the Event Store storage
    networks:
      - ourNetwork

  eureka-1:
    image: mindaugasjasiunas/eureka-server
    container_name: eureka1
    environment:
      server.port: 8761
      eureka.instance.hostname: eureka-1
      eureka.client.service-url.defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
      spring.rabbitmq.host: rabbitMQ
    ports:
      - 8761:8761
    networks:
      - ourNetwork

  eureka-2:
    image: mindaugasjasiunas/eureka-server
    container_name: eureka2
    environment:
      server.port: 8762
      eureka.instance.hostname: eureka-2
      eureka.client.service-url.defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
      spring.rabbitmq.host: rabbitMQ
    ports:
      - 8762:8762
    networks:
      - ourNetwork

  packages-app:
    image: mindaugasjasiunas/packages-service
    container_name: packages-app
    environment:
      PORT: 8080
      spring.data.mongodb.uri: mongodb://root:rootroot@mongoDB:27017/packagesservicedb?authSource=admin&retryWrites=true&w=majority
      axon.axonserver.servers: axonFramework:8124
      spring.rabbitmq.host: rabbitMQ
      eureka.client.service-url.defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
      eureka.instance.prefer-ip-address: true # to ignore 'eureka.instance.hostname=localhost' in application.properties & to get routed in Spring Cloud API Gateway
    ports:
      - 8080:8080
    depends_on:
      - axonFramework
      - mongoDB
      - rabbitMQ
    networks:
      - ourNetwork
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'

  delivery-app:
    image: mindaugasjasiunas/delivery-service
    container_name: delivery-app
    environment:
      PORT: 8081
      axon.axonserver.servers: axonFramework:8124
      eureka.client.service-url.defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
      eureka.instance.prefer-ip-address: true # to ignore 'eureka.instance.hostname=localhost' in application.properties & to get routed in Spring Cloud API Gateway
    ports:
      - 8081:8081
    depends_on:
      - packages-app
    networks:
      - ourNetwork
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'

  payment-app:
    image: mindaugasjasiunas/payment-service
    container_name: payment-app
    environment:
      PORT: 8082
      axon.axonserver.servers: axonFramework:8124
      eureka.client.service-url.defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
      eureka.instance.prefer-ip-address: true # to ignore 'eureka.instance.hostname=localhost' in application.properties & to get routed in Spring Cloud API Gateway
    ports:
      - 8082:8082
    depends_on:
      - packages-app
    networks:
      - ourNetwork
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'

  postgreSQL:
    image: postgres
    container_name: postreSQL-ourUserDB
    ports:
      - 5432:5432
      - 49153:49153
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: ouruserdb
  #    volumes:
  #      - /home/linuxmachine/postgrestorage:/var/lib/postgresql/data
    networks:
      - ourNetwork

  #  adminer:
  #    image: adminer
  #    restart: always
  #    ports:
  #      - 8080:8080

  users-service:
    image: mindaugasjasiunas/users-service
    container_name: users-service
    ports:
      - 8083:8083
    restart: always
    environment:
      PORT: 8083
      spring.r2dbc.url: r2dbc:postgresql://postgreSQL:5432/ouruserdb
      spring.rabbitmq.host: rabbitMQ
      eureka.client.service-url.defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
      eureka.instance.prefer-ip-address: true # to ignore 'eureka.instance.hostname=localhost' in application.properties & to get routed in Spring Cloud API Gateway
    networks:
      - ourNetwork
    depends_on:
      - postgreSQL
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'

  api-gateway:
    image: mindaugasjasiunas/api-gateway
    container_name: api-gateway
    ports:
      - 9090:9090
    environment:
      SPRING_PROFILES_ACTIVE: local
      eureka.client.service-url.defaultZone: http://eureka-1:8761/eureka, http://eureka-2:8762/eureka
      spring.rabbitmq.host: rabbitMQ
      # we can define routes here (overrides all that is configured in properties)
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: users-home-additional
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: lb://users-service/
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/home-sweet-home
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[1]: Method=GET
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: RemoveRequestHeader=Cookie
#      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[1]: RewritePath=/home-sweet-home, /
    networks:
      - ourNetwork
    restart: always
    depends_on:
      - eureka-1
      - eureka-2
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'

  parcel-frontend:
    image: parcel-frontend-image
    container_name: parcel-frontend
    ports:
      - 8088:80
    networks:
      - ourNetwork
    environment:
      API_URL: http://172.17.0.1:9090/
#      API_LOGIN_URL: http://api-gateway:9090/login # net::ERR_NAME_NOT_RESOLVED
#      API_LOGIN_URL: http://docker.host.internal:9090/login # net::ERR_NAME_NOT_RESOLVED
      API_LOGIN_URL: http://172.17.0.1:9090/login
      API_REGISTER_URL: http://172.17.0.1:9090/register
      API_REFRESH_URL: http://172.17.0.1:9090/resettoken
      API_PACKAGES_URL: http://172.17.0.1:9090/parcels
      API_PACKAGE_TRACKING_URL: http://172.17.0.1:9090/tracking/
      API_CREATE_PACKAGE_URL: http://172.17.0.1:9090/new

  courier-frontend:
    image: courier-frontend-image
    container_name: courier-frontend
    ports:
      - 8099:80
    networks:
      - ourNetwork
    environment:
      API_URL: http://172.17.0.1:9090/
      #      API_LOGIN_URL: http://api-gateway:9090/login # net::ERR_NAME_NOT_RESOLVED
      #      API_LOGIN_URL: http://docker.host.internal:9090/login # net::ERR_NAME_NOT_RESOLVED
      API_LOGIN_URL: http://172.17.0.1:9090/login
      API_REFRESH_URL: http://172.17.0.1:9090/resettoken
      API_PACKAGES_URL: http://172.17.0.1:9090/parcels
      API_PACKAGES_COUNT_URL: http://172.17.0.1:9090/new


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - data01:/usr/share/elasticsearch/data #  The volume mount ensures that elasticsearch data is persisted across container restarts.
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - ourNetwork

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.0
    container_name: logstash
    ports:
      - 9600:9600
      - 12201:12201/udp
    environment:
      - logger.level = DEBUG
      - ELASTICSEARCH_HOSTS = http://elasticsearch:9200
      - LS_JAVA_OPTS = "-Xmx256m -Xms256m"
    volumes:
#      - /home/workstation/Desktop/ELK/testing-elk/logstash:/logstash_dir #otherwise error: No config files found in path /logstash_dir/logstash.conf
      - /home/workstation/intellij projects/microservices-spring-boot-angular/reactive packages service/src/main/docker/ELK/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro # overrides 'main' pipeline config file with our config file
#      - ~/settings/logstash.yml:/usr/share/logstash/config/logstash.yml # to override configuration
    depends_on:
      - elasticsearch
    networks:
      - ourNetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS = http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - ourNetwork

  filebeat: # reads docker containers logs
    container_name: filebeat
    image:
      docker.elastic.co/beats/filebeat:7.7.0
    volumes:
      - /home/workstation/intellij projects/microservices-spring-boot-angular/reactive packages service/src/main/docker/ELK/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file (:ro - read only mount)
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    networks:
      - ourNetwork # make sure on the same network as ELK stack - otherwise error connecting to redis-cache:6379

  redis-cache: # buffer
    image: redis:6.2
    container_name: redis-cache
    #    ports:
    #      - 6379:6379
    networks:
      - ourNetwork # make sure on the same network as ELK stack - otherwise error connecting redis-cache:6379

volumes:
  data01:
    driver: local

networks:
  ourNetwork:
    driver: bridge
