version: '3.8'
services:
  rabbitMQ: # Spring Cloud Config already has it. duplication.
    image: rabbitmq:3-management
    container_name: rabbitmq-spring-cloud-config-server
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongoDB:
    image: mongo
    container_name: reactive-packages-service-mongoDB
    ports:
      - 27017:27017
#      - '27017-27019:27017-27019'
#    volumes:
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro # initial script (executes only if /data/db is empty in container - never empty = never executes
#      - ~/home/workstation/dockerstorage/mongodbstorage:/data/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: packagesservicedb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot

  # Database Manager
#  mongo-express:
#    image: mongo-express
#    ports:
#      - 8099:8081
#    depends_on:
#      - mongo
#    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: express
#      ME_CONFIG_BASICAUTH_PASSWORD: 123456
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: rootroot
#    links:
#      - mongoDB